//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Likja.Tid {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TidStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TidStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Likja.Tid.TidStrings", typeof(TidStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad command or wrong parameters..
        /// </summary>
        internal static string P1 {
            get {
                return ResourceManager.GetString("P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occur. Send this error to the author:.
        /// </summary>
        internal static string P2 {
            get {
                return ResourceManager.GetString("P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Args:.
        /// </summary>
        internal static string P3 {
            get {
                return ResourceManager.GetString("P3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:.
        /// </summary>
        internal static string P4 {
            get {
                return ResourceManager.GetString("P4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show.
        /// </summary>
        internal static string P5 {
            get {
                return ResourceManager.GetString("P5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        internal static string P6 {
            get {
                return ResourceManager.GetString("P6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .tid.
        /// </summary>
        internal static string R1 {
            get {
                return ResourceManager.GetString("R1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been removed from the list..
        /// </summary>
        internal static string R10 {
            get {
                return ResourceManager.GetString("R10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `tid` is a command-line task/issue manager.  Author: kimerran (http://github.com/kimerran).
        /// </summary>
        internal static string R11 {
            get {
                return ResourceManager.GetString("R11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usage: tid &lt;command&gt; args.
        /// </summary>
        internal static string R12 {
            get {
                return ResourceManager.GetString("R12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available commands:.
        /// </summary>
        internal static string R13 {
            get {
                return ResourceManager.GetString("R13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to init   Initialize the directory for usage.
        /// </summary>
        internal static string R14 {
            get {
                return ResourceManager.GetString("R14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add    Adds a new task.
        /// </summary>
        internal static string R15 {
            get {
                return ResourceManager.GetString("R15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit   Edits an existing task.
        /// </summary>
        internal static string R16 {
            get {
                return ResourceManager.GetString("R16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show   Shows all the tasks.
        /// </summary>
        internal static string R17 {
            get {
                return ResourceManager.GetString("R17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start  Starts the task.
        /// </summary>
        internal static string R18 {
            get {
                return ResourceManager.GetString("R18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done   Mark the task as &apos;done&apos;.
        /// </summary>
        internal static string R19 {
            get {
                return ResourceManager.GetString("R19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command not supported..
        /// </summary>
        internal static string R2 {
            get {
                return ResourceManager.GetString("R2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to purge  Remove the task from the list.
        /// </summary>
        internal static string R20 {
            get {
                return ResourceManager.GetString("R20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tid init &lt;Project Name&gt; | ex. tid init Liztr.
        /// </summary>
        internal static string R21 {
            get {
                return ResourceManager.GetString("R21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tid add &lt;Task details&gt; | ex. tid add &quot;As a user, I should be able to login&quot;.
        /// </summary>
        internal static string R22 {
            get {
                return ResourceManager.GetString("R22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tid start &lt;Task ID&gt; | ex. tid start 001.
        /// </summary>
        internal static string R23 {
            get {
                return ResourceManager.GetString("R23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tid done &lt;Task ID&gt; | ex. tid done 001.
        /// </summary>
        internal static string R24 {
            get {
                return ResourceManager.GetString("R24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tid purge &lt;Task ID&gt; | ex. tid purge 001.
        /// </summary>
        internal static string R25 {
            get {
                return ResourceManager.GetString("R25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tid edit &lt;Task ID:New Details&gt; | ex. tid edit &quot;002:As an admin, I should be able to register new user.&quot;.
        /// </summary>
        internal static string R26 {
            get {
                return ResourceManager.GetString("R26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize this directory first. Run `tid help` for more info..
        /// </summary>
        internal static string R3 {
            get {
                return ResourceManager.GetString("R3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task ID {0} not found..
        /// </summary>
        internal static string R4 {
            get {
                return ResourceManager.GetString("R4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This directory is already initialized..
        /// </summary>
        internal static string R5 {
            get {
                return ResourceManager.GetString("R5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name should be at least three letters..
        /// </summary>
        internal static string R6 {
            get {
                return ResourceManager.GetString("R6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task {0} has been added..
        /// </summary>
        internal static string R7 {
            get {
                return ResourceManager.GetString("R7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been started..
        /// </summary>
        internal static string R8 {
            get {
                return ResourceManager.GetString("R8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been marked as done..
        /// </summary>
        internal static string R9 {
            get {
                return ResourceManager.GetString("R9", resourceCulture);
            }
        }
    }
}
